package com.example.openinapp.model

data class OverallUrlChart(
    val DateList: Int = 0,
)
//                             val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0,
//                           val : Int = 0)